export const ProductSchema = {
  name: "Product",
  properties: {
    _id: "int",
    codSefaz: "string",
    descricao: "string",
    codigo: "string",
    cean: "string",
    cbarra: "string",
    descricao: "string",
    ncm: "string",
    cest: "string",
    cfop: "int",
    unidade: "string",
    valor: "double",
    codigoAnp: "string",
    origem: "string",
    cstIcms: "string",
    cstpiscofins: "string",
    ativo: "bool",
    quantidade: "int?",
  },
  primaryKey: "_id",
};
